spring:
   thymeleaf:
      cache: false
   
   jpa:
      show-sql: true

      hibernate:
         naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
   
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog
      username: root
      password: Password@123

server:
   port: 8089

logging:
   pattern:
      console: "%-5level %logger{36} - %msg%n"
   level:
      org.springframework: INFO
      org.springframework.jdbc: INFO
      com.heytusar: INFO
      root: INFO
